name: Debian VPS via SSH

on:
  workflow_dispatch:

jobs:
  debian-vps:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        authorized-keys: ${{ secrets.SSH_PUBLIC_KEY }}
